[package]
name = "example-l2"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = { version = "1.12", features = ["attributes"] }
ethers = "2.0.1"
ethers-core = "2.0.1"
rand = "0.8.5"
